version: '3'

services:
  reddio:
    image: ghcr.io/reddio-com/reddio:latest
    restart: always
    volumes:
      - ./data/reddio_db:/reddio_db
      - ./data/yu:/yu
    ports:
      # p2p port
      -  8887:8887
      # starknet port
      -  9091:9091
      # pprof port
      -  8081:8081